---
  - name: Installed AD Controller
    win_feature:
      name: AD-Domain-Services
      state: present

  - name: Install dns
    win_domain:
      dns_domain_name: "{{ ad_domain_name }}"
      safe_mode_password: "{{ ad_safe_mode_password }}"

  - name: Setting up AD Controller
    win_domain_controller:
      dns_domain_name: "{{ ad_domain_name }}"
      safe_mode_password: "{{ ad_safe_mode_password }}"
      domain_admin_user: "{{ad_admin_user}}"
      domain_admin_password: "{{ad_admin_password}}"
      state: domain_controller

# - name: Restarting the AD controller
#   win_reboot: 

  - name: Printing Domain List after win_reboot
    win_command: nltest /dclist:"{{ ad_domain_name }}"


#    jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==
...

