---
  - name: Install Packages
    win_chocolatey: 
      name: "{{ item }}"
      params: "{{ parameters }}"
      state: present
    with_items: "{{ package_name}}"
    
  - name: Enable Services
    win_service: 
      name: "{{ service_name }}"

  - name: Setup firewall
    win_firewall_rule:
      action: allow
      direction: out
      localport: "{{ local_port}}"
      name: port_22
      protocol: "{{ protocol_name }}"
...
